### ISSUE TITLE
Unable to use built ISO & testing it out on UTM

### ISSUE THREAD

**Issue by cdrage** [osbuild/bootc-image-builder#112]
My Containerfile:

```
FROM quay.io/centos-bootc/fedora-bootc:eln
RUN echo "root:root" | chpasswd
RUN echo "hello" > hello.txt
```

I then proceeded to build the .iso using the standard bootc-image-builder command.

After installing the .iso within UTM, it successfully installed! After however, the OS got stuck on this screen:

<img width="827" alt="Screenshot 2024-01-11 at 2 15 46 PM" src="https://github.com/osbuild/bootc-image-builder/assets/6422176/8d04b97c-dafb-4a77-a9c1-8130a594c9b0">

Trying to diagnose now and get more logs. Opened this issue up for brevity.

**Comment by runcom** [comment]
running the README and producing and running a qcow2 on an m2 air gives the same

**Comment by cdrage** [comment]
Closing as I am no longer experiencing this after switching to the latest images.
