### ISSUE TITLE
`Kickstart insufficient` when running with libvirt

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/bootc-image-builder#116]
@noelmiller [reported in Discord](https://discordapp.com/channels/1072614816579063828/1192504002252914791/1195068669391290509) that when the ISO is run using virt-manager, the installation fails on the `Kickstart insufficient` error.

![image](https://github.com/osbuild/bootc-image-builder/assets/119861/b9ebaadd-2094-469b-a504-362c5776c484)

Interestingly enough, this error does not happen when he used `qemu` directly (the installation failed later in this case, see #114).

Note that Noel used `ghcr.io/ublue-os/bluefin:latest`. I'm wondering if the same issue exists also with bootc images. Also, I wonder what's the different between libvirt and qemu. We should definitely test whether ISO with bootc images inside work under libvirt.

**Comment by supakeen** [comment]
I'll take a look at this.

Is there any additional information in the Discord link? I can't access that.

**Comment by noelmiller** [comment]
> I'll take a look at this.
> 
> Is there any additional information in the Discord link? I can't access that.

@ondrejbudai gave a good summary on this. I'll be doing some testing shortly to see if I can use quay.io/centos-bootc/fedora-bootc:eln as an ISO with virt-manager and post my results here. I'll also check if using EFI vs BIOS makes a difference.

**Comment by noelmiller** [comment]
Using `UEFI x86_64: /usr/share/edk/ovmf/OVMF_CODE.fd` in Virt-Manager, I was able to successfully get the installation to start. Still getting the same error for Bluefin as in https://github.com/osbuild/bootc-image-builder/issues/114
![image](https://github.com/osbuild/bootc-image-builder/assets/4983138/77b6ac35-7572-4531-bb12-8077977e53a4)

I will test quay.io/centos-bootc/fedora-bootc:eln shortly after I build it.

**Comment by noelmiller** [comment]
So `quay.io/centos-bootc/fedora-bootc:eln` does experience the same behavior when booting with BIOS
![image](https://github.com/osbuild/bootc-image-builder/assets/4983138/41b2b134-93cb-49b0-9319-ceb304a92be8)

It does not happen when using UEFI.

**Comment by supakeen** [comment]
This PR solves this issue and is currently in the merge queue: https://github.com/osbuild/images/pull/360

**Comment by supakeen** [comment]
The PR has been merged, a second PR which makes this better is here: https://github.com/osbuild/images/pull/363

**Comment by noelmiller** [comment]
I tested recently with a default BIOS configuration and it works fine. Feel free to close this issue @ondrejbudai

**Comment by ochosi** [comment]
Awesome! Closing...
