### ISSUE TITLE
Lack of Documentation Regarding AMI Import

### ISSUE THREAD

**Issue by noelmiller** [osbuild/bootc-image-builder#127]
Hi Folks! 

I had an issue importing my AMI using this tool because I didn't realize having a vmimport service role in my AWS account was required. 

Here is the documentation I used from Amazon so I could get the AMI to import: https://docs.aws.amazon.com/vm-import/latest/userguide/required-permissions.html

Would you like me to add this to the README.md as a dependency for getting it to work?

Thanks, 

Noel Miller

**Comment by bcl** [comment]
Sure!
