### ISSUE TITLE
Iso installer does not work with `quay.io/centos-bootc/centos-bootc:stream9`

### ISSUE THREAD

**Issue by mvo5** [osbuild/bootc-image-builder#157]
The installer fails with the following error:
![Screenshot from 2024-01-26 11-49-07](https://github.com/osbuild/bootc-image-builder/assets/914418/76b3e144-21fb-45a6-ae0a-9cb7b579ce49)

**Comment by mvo5** [comment]
The issue is that /boot is build as xfs and the grub2-mkconfig in centos cannot read the format.

**Comment by ondrejbudai** [comment]
Fixed by #338
