### ISSUE TITLE
setting default systemd target in the image isn't honored

### ISSUE THREAD

**Issue by runcom** [osbuild/bootc-image-builder#183]
Running an image that has `RUN systemctl set-default graphical.target` doesn't produce a qcow2 that actually has graphical.target as default target - not sure where the problem is (bib or bootc actually) so forgive me if it's the wrong repo and I can move it where appropriate.
The kiosk-demo example is a reproducer for me https://github.com/CentOS/centos-bootc-layered/pull/36/files#diff-a61a6be8ca56bc4a3808309e0191b9e8f8bbbf1b755d4cb7837afdba44857775 and just boots into cmdline mode

**Comment by cgwalters** [comment]
This works for me now.  I bet what you hit here was the same thing as https://github.com/CentOS/centos-bootc/issues/167

Tentatively closing, feel free to reopen if you find otherwise.

**Comment by runcom** [comment]
it does work now using bootc self-install https://github.com/osbuild/bootc-image-builder/issues/168#issuecomment-1921900660 

thanks!
