### ISSUE TITLE
Add instructions for reproducing issues without BIB

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/bootc-image-builder#186]
Seeing #183 and #168 (and [this comment](https://github.com/osbuild/bootc-image-builder/issues/168#issuecomment-1921900660) in particular), I think it would a great troubleshooting first step for issues relating to image building.  Not sure where we would put this, developer docs or the issue template (both?), but I can imagine we'll have a lot of these kinds of situations where it's not clear if an issue is coming from the way bib is building the image or it's from the container itself.  Instructions for taking bib out of the equation and "manually" making a simple disk image would save a lot of time.

**Comment by cgwalters** [comment]
I think we already have instructions for the [direct bootc install](https://github.com/containers/bootc/blob/main/docs/install.md#executing-bootc-install) (also, today it's what `podman-bootc run` uses, though I do want to add a `run --via-bib` or so to also test that); what I'm stumbling on more is trying to debug the bib pipeline...if someone in the know can type that up somewhere that'd be awesome.

I managed to do this:

`podman run <bib> --entrypoint bash` to get a shell

In that shell, run `bootc-image-builder` directly to reproduce a failure.  Now...the intermediate stage is GC'd, and I wanted to try injecting e.g. `strace` or `env RUST_LOG=debug` etc into the command.

I managed to do `bootc-image-builder manifest quay.io/flightctl/flightctl-agent-centos:bootstrap > /tmp/manifest.json` to generate a manifest, but `osbuild --store /store --output-directory /output /tmp/manifest.json` just...fetches the container and doesn't do anything else?

**Comment by cgwalters** [comment]
My next step here would be to try using `osbuild --break` if the second part worked

**Comment by achilleas-k** [comment]
> I think we already have instructions for the [direct bootc install](https://github.com/containers/bootc/blob/main/docs/install.md#executing-bootc-install)

Perfect.  I'll add it.  I think it's still useful to have a troubleshooting guide in this repository, even if it just links out to other guides, because it seems a lot of users come to bib first when they have issues (or maybe I'm just unaware of the ones that don't).  Either way, it's useful to have a guide like this that we can point users to for information gathering.
Opened https://github.com/osbuild/bootc-image-builder/pull/222
