### ISSUE TITLE
We are slowly moving to zstd:chunked format for container images but osbuild is not handling it.

### ISSUE THREAD

**Issue by rhatdan** [osbuild/bootc-image-builder#236]
ostree container image deploy --imgref=ostree-unverified-image:dir:/tmp/tmpxu_tjilg/image --stateroot=default --target-imgref=ostree-unverified-registry:quay.io/rhatdan/lamp:latest --karg=rw --karg=console=tty0 --karg=console=ttyS0 --karg=root=LABEL=root --sysroot=/run/osbuild/tree
error: Performing deployment: Importing: Unhandled layer type: application/vnd.oci.image.layer.v1.tar+zstd

This happens when trying to convert "quay.io/rhatdan/lamp:latest".

Which was pushed using zstd:chunked format.

**Comment by rhatdan** [comment]
@giuseppe FYI

**Comment by rhatdan** [comment]
@cgwalters FYI?  Is this an issue with ostree not supporting other formats, or does it just need to be updated with the lastes containers-image.

**Comment by cgwalters** [comment]
It's unrelated to bib, you'd see the same error from `bootc switch` for example.

**Comment by cgwalters** [comment]
Moving this to https://github.com/ostreedev/ostree-rs-ext/issues/608
