### ISSUE TITLE
ISO install Error using virt-install :Error validating install location: Could not find an installable distribution at URL '/var/lib/libvirt/images/install.iso'

### ISSUE THREAD

**Issue by chunfuwen** [osbuild/bootc-image-builder#265]
```
step 1 : generate iso file:

podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v $(pwd)/config.json:/config.json -v $(pwd)/output:/output quay.io/centos-bootc/bootc-image-builder:latest quay.io/centos-bootc/fedora-bootc:eln --type iso --tls-verify  --chown 107:107

step 2:  use virt-install install iso file:

virt-install --connect qemu:///system -n imagevm --hvm --accelerate -r 3096 --vcpus=3 --os-variant rhel9.0 --disk path=/var/lib/libvirt/images/testimgevm.qcow2,bus=virtio,format=qcow2,size=10 --network network=default,model=virtio  --location /var/lib/libvirt/images/install.iso --debug --memballoon model=virtio --cpu host,disable=vmx --graphics vnc --video virtio --machine q35


Result : virt-install throw error and terminate the installation


```

**Comment by chunfuwen** [comment]
look like the issue is already there

**Comment by chunfuwen** [comment]
root@hp-dl360g9-16 bootc-image-builder]# isoinfo -d -i /var/lib/libvirt/images/install.iso 
CD-ROM is in ISO 9660 format
System id: LINUX
Volume id: Container-Installer-x86_64
Volume set id: 
Publisher id: 
Data preparer id: XORRISO-1.5.6 2023.06.07.180001, LIBISOBURN-1.5.6, LIBISOFS-1.5.6, LIBBURN-1.5.6
Application id: 
Copyright File id: 
Abstract File id: 
Bibliographic File id: 
Volume set size is: 1
Volume set sequence number is: 1
Logical block size is: 2048
Volume size is: 873976
El Torito VD version 1 found, boot catalog is in sector 57
Joliet with UCS level 3 found
Rock Ridge signatures version 1 found
Eltorito validation header:
    Hid 1
    Arch 0 (x86)
    ID ''
    Key 55 AA
    Eltorito defaultboot header:
        Bootid 88 (bootable)
        Boot media 0 (No Emulation Boot)
        Load segment 0
        Sys type 0
        Nsect 4
        Bootoff 3A 58

**Comment by ondrejbudai** [comment]
Shouldn't `--location /var/lib/libvirt/images/install.iso` be `--cdrom /var/lib/libvirt/images/install.iso`?

**Comment by chunfuwen** [comment]
For general iso such as RHEL ISO, it looks like support both of them : --cdrom, --location.
One more information I gotten is that Device Edge Iso support location, see details:
[https://github.com/openshift/microshift/blob/main/docs/user/getting_started.md](url)

**Comment by chunfuwen** [comment]
```
[root@xx images]# virt-install --connect qemu:///system -n imageisovm --hvm --accelerate -r 3096 --vcpus=3 --os-variant rhel9.0 --disk path=/var/lib/libvirt/images/testimgevm2.qcow2,bus=virtio,format=qcow2,size=10 --network network=default,model=virtio  --location /var/lib/libvirt/images/fedora.iso --debug --memballoon model=virtio --cpu host,disable=vmx --graphics vnc --video virtio --machine q35
[Fri, 15 Mar 2024 04:27:39 virt-install 1495666] DEBUG (cli:204) Version 4.1.0 launched with command line: /usr/bin/virt-install --connect qemu:///system -n imageisovm --hvm --accelerate -r 3096 --vcpus=3 --os-variant rhel9.0 --disk path=/var/lib/libvirt/images/testimgevm2.qcow2,bus=virtio,format=qcow2,size=10 --network network=default,model=virtio --location /var/lib/libvirt/images/fedora.iso --debug --memballoon model=virtio --cpu host,disable=vmx --graphics vnc --video virtio --machine q35
[Fri, 15 Mar 2024 04:27:39 virt-install 1495666] DEBUG (virtinstall:212) Distilled --network options: ['network=default,model=virtio']
[Fri, 15 Mar 2024 04:27:39 virt-install 1495666] DEBUG (virtinstall:142) Distilled --disk options: ['path=/var/lib/libvirt/images/testimgevm2.qcow2,bus=virtio,format=qcow2,size=10']
[Fri, 15 Mar 2024 04:27:39 virt-install 1495666] DEBUG (cli:217) Requesting libvirt URI qemu:///system
[Fri, 15 Mar 2024 04:27:39 virt-install 1495666] DEBUG (connection:128) libvirt URI versions library=9.5.0 driver=9.5.0 hypervisor=8.0.0
[Fri, 15 Mar 2024 04:27:39 virt-install 1495666] DEBUG (connection:109) Fetched capabilities for qemu:///system: <capabilities>

  <host>
    <uuid>4c4c4544-0056-4610-8031-b9c04f504432</uuid>
...
```

**Comment by bcl** [comment]
Did you try `--cdrom`? It looks like you don't really need to use `--location` in your case (it is required if you are trying to modify the kernel cmdline), IIRC virt-install has some strong opinions about storage location and what it can use for `--location`. You could also try using qemu-kvm directly.

**Comment by chunfuwen** [comment]
Yes ,I tried --cdrom, and it worked as expected.
But I wonder whether it is a potential issue that we don't support --location option.

**Comment by ondrejbudai** [comment]
Hmm, so `--location` is used to install from a "Distribution tree installation source. virt-install can recognize certain distribution trees and fetches a bootable kernel/initrd pair to launch the install.".

I wonder if the ISO that we produce is not recognized as a distribution tree... It's good to know that `--cdrom` works, though. :) @supakeen Have you ever seen anything like this while dealing with ISOs?

**Comment by supakeen** [comment]
As far as I'm ware you should use `--cdrom` for an ISO. `--location` is for other types of content (distribution trees as @ondrejbudai points out).

**Comment by supakeen** [comment]
So, `--location` *does* work with the RHEL 9.3 ISO's but *not* with Fedora ISOs.

**Comment by chunfuwen** [comment]
with --location ,I use fedora iso from :https://download.fedoraproject.org/pub/fedora/linux/releases/39/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-39-1.5.iso
And virt-install can succeed afterwards installing procedure, and there is no output " Error validating install location"

**Comment by supakeen** [comment]
Right so it might work for a subset of ISOs in the Fedora project as well (not Server, or IoT, which are the ones I had laying around).

**Comment by bcl** [comment]
Distribution tree usually means something that looks like this: https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/ but I think virt-install also has some code to grab that info from isos that it recognizes, but I'd have to go dig through their code to be sure. So unless you really need to append things to the kernel cmdline the right thing to use is `--cdrom` or `--hda`

**Comment by ggiguash** [comment]
The workaround for this problem is to examine the produced ISO to determine kernel and initrd paths to be passed explicitly in virt-install command line.
```
--location "/path/to/cos9-bootc.iso,kernel=images/pxeboot/vmlinuz,initrd=images/pxeboot/initrd.img"
--osinfo detect=on
```

Nevertheless, this is a limitation that should be fixed, IMO.

**Comment by DAWEI-73** [comment]
> Yes ,I tried --cdrom, and it worked as expected. But I wonder whether it is a potential issue that we don't support --location option.

I have the same question install bclinux（The location must be the root directory of an install tree.）。then I found the iso don't have .treeinfo file。maybe your iso file also missing treeinfo
