### ISSUE TITLE
Build AMI and vmdk image failed today

### ISSUE THREAD

**Issue by henrywang** [osbuild/bootc-image-builder#285]
Build ami or vmdk image with command:
`sudo podman run --rm -it --privileged --pull=newer --tls-verify=false --security-opt label=type:unconfined_t --env AWS_ACCESS_KEY_ID=***** --env AWS_SECRET_ACCESS_KEY=***** quay.io/centos-bootc/bootc-image-builder:latest --type ami --target-arch x86_64 --aws-ami-name bootc-bib-centos-stream-9-x86_64-ahkv --aws-bucket bootc-bib-images --aws-region us-east-1 quay.io/rhel-edge/centos-bootc-test:ahkv`

Failed with error log:
```
time="2024-03-19T05:46:12Z" level=fatal msg="reading blob sha256:1dc7aacdec3e520054c9e6e886854e1e926e4cc5ea3c6c11c8cbb189d1366480: write /var/tmp/container_images_1731751202: no space left on device"

time="2024-03-19T05:46:13Z" level=error msg="Unable to write system event: \"write unixgram @4d5da->/run/systemd/journal/socket: sendmsg: no such file or directory\""

Error: tmp-container-deploy-76271631750863: image not known

Traceback (most recent call last):

  File "/run/osbuild/bin/org.osbuild.container-deploy", line 82, in main

    subprocess.run(

  File "/usr/lib64/python3.12/subprocess.py", line 571, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['skopeo', 'copy', 'containers-storage:[overlay@/run/osbuild/containers/storage+/run/containers/storage]c8582e801dbbb9f64f39cb1332ee7588b82baa6706eb53aad9d8ee6f0d8d84f2', 'containers-storage:tmp-container-deploy-76271631750863']' returned non-zero exit status 1.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/run/osbuild/bin/org.osbuild.container-deploy", line 96, in <module>

    r = main(args["inputs"], args["tree"], args["options"])

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/run/osbuild/bin/org.osbuild.container-deploy", line 79, in main

    with contextlib.ExitStack() as cm:

  File "/usr/lib64/python3.12/contextlib.py", line 598, in __exit__

    raise exc_details[1]

  File "/usr/lib64/python3.12/contextlib.py", line 583, in __exit__

    if cb(*exc_details):

       ^^^^^^^^^^^^^^^^

  File "/usr/lib64/python3.12/contextlib.py", line 466, in _exit_wrapper

    callback(*args, **kwds)

  File "/usr/lib64/python3.12/subprocess.py", line 571, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['podman', 'rmi', 'tmp-container-deploy-76271631750863']' returned non-zero exit status 1.
````
The full log can be found from http://artifacts.osci.redhat.com/testing-farm/b524aa3a-d0dc-4929-9e8a-94e0f09fcb6f/

This issue didn't exist yesterday. Something changed in bootc-image-builder image today?

**Comment by chunfuwen** [comment]
this morning , I succeed to build out vmdk format image

[root@xx bootc-image-builder]# sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /root/workdir/bootc-image-builder/config.json:/config.json  -v /root/workdir/bootc-image-builder/output:/output  quay.io/centos-bootc/bootc-image-builder:latest  quay.io/centos-bootc/centos-bootc:stream9 --type vmdk --tls-verify=false  --chown 107:107
Generating manifest manifest-vmdk.json
DONE
Building manifest-vmdk.json
starting -Pipeline source org.osbuild.containers-storage: 05f113f7236f1d9a1101e72d7ca23ba59dd509281a1f932adfa7610898532c89
Build
  root: <host>
Pipeline build: c09074474c35e4d437ae1f433aa8c8bb7f7652a68b36664d3734711dd1e09f3d
Build
  root: <host>
  runner: org.osbuild.fedora38 (org.osbuild.fedora38)
org.osbuild.container-deploy: 398d5adc01896472bdabec1a225ce31ca9c8c755501deaa6ab6bf247104bddba {
  "exclude": [
    "/sysroot"
  ]
}
...
⏱  Duration: 82s
manifest - finished successfullybuild:    	c09074474c35e4d437ae1f433aa8c8bb7f7652a68b36664d3734711dd1e09f3d
ostree-deployment:	fcd577f7b038fc334b7d4d61f6413a01f9c8290d9ba8f03f51dd9725fdabc2aa
image:    	5c4c9b8aa9ffd14195d46a758e753e4cf3322f807b99c0d6a105a9d5ce149c60
qcow2:    	afe76ad6ace81f405498c43c0c1ea1dbb11276efee3b0b267d5b940fe47cb6c2
vmdk:     	26e319ff091b6022dd2e2d3130be0e8313ce6a6214300375be3b728209c0e150
ovf:      	069f6ae848792bfdc13a11ab0fb5f19d46d698d7e98fec4ac803086b0040cb65
archive:  	147afd2e889e92e9f8fdc423b66e2b187afcfe601393a5d45a25cca161e4a023
Build complete!
Results saved in
.

**Comment by henrywang** [comment]
@chunfuwen Did you try `--target-arch x86_64` arg when you build image? Thanks.

**Comment by henrywang** [comment]
And this issue only exists on x86_64. I mean run bootc-image-builder image on x86_64 machine. But can't find this issue when run bootc-image-builder image on aarch64.

**Comment by chunfuwen** [comment]
Just tried ami and vmdk on local x86 machine with --target-arch x86_64 ,image can be generated successfully on both situations.
```
sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /root/workdir/bootc-image-builder/config.json:/config.json -v /root/workdir/bootc-image-builder/output:/output quay.io/centos-bootc/bootc-image-builder:latest quay.io/centos-bootc/centos-bootc:stream9 --type vmdk --target-arch x86_64 --tls-verify=false --chown 107:107

sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /root/workdir/bootc-image-builder/config.json:/config.json -v /root/workdir/bootc-image-builder/output:/output quay.io/centos-bootc/bootc-image-builder:latest quay.io/centos-bootc/centos-bootc:stream9 --type ami --target-arch x86_64 --tls-verify=false --chown 107:107

```

**Comment by supakeen** [comment]
The error on the first line is `time="2024-03-19T05:46:12Z" level=fatal msg="reading blob sha256:1dc7aacdec3e520054c9e6e886854e1e926e4cc5ea3c6c11c8cbb189d1366480: write /var/tmp/container_images_1731751202: no space left on device"`

The host system ran out of disk space.

**Comment by henrywang** [comment]
The runner has enough disk space in this case:
```
df -Th
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  4.0M     0  4.0M   0% /dev
tmpfs          tmpfs     1.8G     0  1.8G   0% /dev/shm
tmpfs          tmpfs     707M   17M  691M   3% /run
/dev/xvda1     xfs       250G  4.3G  246G   2% /
tmpfs          tmpfs     354M     0  354M   0% /run/user/0
```

**Comment by mvo5** [comment]
This looks like fallout from https://github.com/osbuild/osbuild/pull/1649

**Comment by supakeen** [comment]
Yea, you get the same error both when there's not enough *RAM* or not enough *disk*. In this case the filesystem lives on a tmpfs.

**Comment by achilleas-k** [comment]
@henrywang Can you test with the RPM from https://github.com/osbuild/osbuild/pull/1673 ?

**Comment by henrywang** [comment]
The testing farm default x86_64 vm is 2 CPU + 4G memory. Do we have recommendation about CPU and memory to use bib? Thanks.

**Comment by henrywang** [comment]
Verified with the osbuild:
```
osbuild-112-1.20240320193749781140.main.29.g345516e8.fc39.noarch              
osbuild-depsolve-dnf-112-1.20240320193749781140.main.29.g345516e8.fc39.noarch 
osbuild-ostree-112-1.20240320193749781140.main.29.g345516e8.fc39.noarch       
osbuild-selinux-112-1.20240320193749781140.main.29.g345516e8.fc39.noarch      
python3-osbuild-112-1.20240320193749781140.main.29.g345516e8.fc39.noarch    
```
Test log: https://github.com/virt-s1/bootc-workflow-test/pull/198
