### ISSUE TITLE
Sample virt-install invocation for eln requires explicit CPU flag

### ISSUE THREAD

**Issue by say-paul** [osbuild/bootc-image-builder#287]
I am trying generate an image  straight-up from readme example:

```
sudo podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/config.json:/config.json \
    -v $(pwd)/output:/output \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type qcow2 \
    --config /config.json \
    quay.io/centos-bootc/fedora-bootc:eln
```
even tried same with : quay.io/centos-bootc/centos-bootc:stream9

On trying to boot I get : 
```
 Error : kernel panic: not syncing: Attempted to kill init! exit code =0x00007f00
```
![image](https://github.com/osbuild/bootc-image-builder/assets/25081859/116613dc-9531-4a5f-a7eb-45e45336b451)

**Comment by mvo5** [comment]
How did you run the image? As a wild guess, maybe `-cpu host` is missing from the qemu commandline(and maybe we need to document this better). The default ELN needs amd64v3 iirc and that is not provided by the default qemu commandline.

**Comment by say-paul** [comment]
@mvo5 yes adding that flag worked, I added a small PR to fix the documentation.
