### ISSUE TITLE
Recommended RAM / GB of memory for podman machine / running bootc-image-builder

### ISSUE THREAD

**Issue by cdrage** [osbuild/bootc-image-builder#322]
We're finding that we are running into building issues if there is too low of memory https://github.com/containers/podman-desktop-extension-bootc/issues/221

2GB it fails.

6GB of RAM it sometimes fails when building something a bit larger

10GB of RAM allocated to the podman machine and it's okay.

Why the need for so much RAM, could we document it in the README as well as what's been the recommended amount of RAM that people have needed to use bootc-image-builder?

**Comment by ondrejbudai** [comment]
Hmm, interesting, we shouldn't be putting anything big on tmpfs nowadays. Can you double-check with the latest image?

`quay.io/centos-bootc/bootc-image-builder:a009d63c77cd8b83d1a3256989043f0047a4f77d`

**Comment by deboer-tim** [comment]
I moved from ~2 weeks ago to test today's image. I've been able to build multiple image types, even on a default 2Gb machine with a few other containers running (!).

It was hard to monitor it the whole time (ISO in particular seems slower than before, ~5min) but the peak I saw was about 700Mb. Are we comfortable that we can keep memory use below this level, and so there would be no special memory requirement going forward?

**Comment by ondrejbudai** [comment]
I think I'm comfortable with it. There was a bug in the stack recently that accidentally put way more stuff than reasonable on tmpfs, but that's no longer the case. Closing for now, feel free to reopen if someone else has a concern, or if there's a failed build due to low memory. :)
