### ISSUE TITLE
No writable /usr/local/

### ISSUE THREAD

**Issue by martinpitt** [osbuild/bootc-image-builder#326]
A "traditional" OSTree system has a symlink /usr/local → ../var/usrlocal, both a standard Fedora CoreOS and also an OCI image converted by `rpm-ostree compose container-encapsulate`.

```
❱❱❱ podman run -it --rm quay.io/fedora/fedora-coreos:stable ls -l /usr/local
lrwxrwxrwx. 2 root root 15 Jan  1  1970 /usr/local -> ../var/usrlocal
```

(`/var/` isn't part of the image, so not showing it).

But the current [Fedora ELN bootc](https://quay.io/repository/centos-bootc/fedora-bootc?tab=tags) containers are missing that symlink -- the `/var/usrlocal/` directory does exist, but `/usr/local/` is a proper directory with just a bunch of directories in them. With that it's not writable:

```
❱❱❱ podman run -it --rm quay.io/centos-bootc/fedora-bootc:eln sh -c 'ls -ld /usr/local; ls -l /usr/local'
drwxr-xr-x. 13 root root 4096 Jan  1  1970 /usr/local
total 44
drwxr-xr-x. 2 root root 4096 Jan  1  1970 bin
drwxr-xr-x. 2 root root 4096 Jan  1  1970 etc
drwxr-xr-x. 2 root root 4096 Jan  1  1970 games
drwxr-xr-x. 2 root root 4096 Jan  1  1970 include
drwxr-xr-x. 2 root root 4096 Jan  1  1970 lib
drwxr-xr-x. 3 root root 4096 Jan  1  1970 lib64
drwxr-xr-x. 2 root root 4096 Jan  1  1970 libexec
drwxr-xr-x. 2 root root 4096 Jan  1  1970 man
drwxr-xr-x. 2 root root 4096 Jan  1  1970 sbin
drwxr-xr-x. 5 root root 4096 Jan  1  1970 share
drwxr-xr-x. 2 root root 4096 Jan  1  1970 src
```

Is that intentional, i.e. is /usr/local/ deprecated? I'm looking for a place where to put additional cockpit extensions. Traditionally we've put them into /usr/local/share/cockpit/.

If that is meant to  not work, then I could look into using a systemd-sysext instead, but it may just be an oversight?

**Comment by cgwalters** [comment]
On Wed, Apr 3, 2024, at 5:08 PM, Martin Pitt wrote:
> A "traditional" OSTree system has a symlink /usr/local → 
> ../var/usrlocal, both a standard Fedora CoreOS and also an OCI image 
> converted by `rpm-ostree compose container-encapsulate`.

This doesn’t have anything to do with bootc-image-builder but with the base image which is produced elsewhere.  Nevertheless I will answer here: the *fundamental* difference is that with bootc we generally  expect you to derive from the image and own OS updates.  So try baking in cockpit extensions instead of installing them via machine local mechanisms.  Does that make sense?

**Comment by martinpitt** [comment]
Right, I'm just not sure where to file bugs for the base images. Also, as quay.io/centos-bootc/centos-bootc:stream9 has the same issue, it feels more like an issue with the container build processs rather than the distro itself.

It's easy enough to fix/work around in a derivation anyway, so this isn't a blocker at all:
```
RUN rm -rf /usr/local; ln -s ../var/usrlocal /usr/local
```
I mostly filed this to discuss whether it is intentional or a bug. Feel free to just close if it's intended to be a "wontfix".

**Comment by cgwalters** [comment]
There's a conceptual clash between Cockpit and bootc; much more than between Cockpit and ostree (as it was emphasized to start).  The emphasis of bootc is on deriving a container image and a git-ops style workflow and avoiding local stateful mutation of OS state as much as possible.  But Cockpit is all about the latter.  Of course, one can make custom ostree, but we in Fedora derivatives have not heavily promoted that; and supporting custom builds is a huge thing with OS/distro wide impact.

Of course, there are things that can make sense here, like using Cockpit to adjust LVM configuration interactively...that's kind of "below" bootc's state (you'd need to craft a systemd unit) and also very amenable to a GUI.  But of course you should also be making the same change in your kickstart so that the monthly full reprovision picks up the change too...

**Comment by martinpitt** [comment]
@cgwalters The clash isn't that bad I think -- most of cockpit's functionality, such as general troubleshooting (looking at logs, failed services, etc.), or starting/supervising/debugging containers or VMs is still valid. Of course one shouldn't muck around on production machines and expect changes to stay, but that isn't specific to bootc or OSTree; rather, it's  defining a policy between "setting up" and "troubleshooting", and defining how much of the former happens with things like pre-built images/containers, Ansible, or manual action. You'd be surprised how much customer demand there still is for interactive manual setup, as much as it saddens me. But it's less of a surprise for desktops and developer machines than for production deployments.

Of course *some* cockpit functionality, such as configuring partitions or applying rpm software updates doesn't apply, and we already implemented some steps to handle that gracefully. E.g. the PackageKit based "Software Updates" page just won't show on ostree.

We got a request to show/do at least basic bootc information/actions in cockpit (show current image, new image availability, so I'm currently [building a CI image](https://github.com/cockpit-project/bots/pull/6171) and enable some projects on it.

**Comment by cgwalters** [comment]
Right.  May be nice to have a cockpit mode that is explicitly "read-only/ephemeral", or at least clearly distinguish things that would cause persistent changes.

So going back down to the low level, am I understanding correctly that these plugins are dynamically downloaded - i.e. if Cockpit detects the system has the feature it loads them?   I think Cockpit should put these in `/var/cache/cockpit/plugins` (or `/var/lib`).  That would work the same across package, ostree, bootc, etc. and I would argue is more "correct" for this.    `/usr/local` is more a place to put binaries the systemd units or admin would invoke, historically.

**Comment by cgwalters** [comment]
But...arguably of course there should be:
```
RUN dnf -y install cockpit && cockpit --install-apps
```

The `--install-apps` would be explicitly designed to run as part of a container build, see what features (lvm, networkmanager, podman, etc.) are in the image, then download them and include them in `/usr/lib/cockpit` or so - explicitly part of the immutable state, the same as `/usr/bin/cockpit-bridge`.

**Comment by martinpitt** [comment]
> am I understanding correctly that these plugins are dynamically downloaded

No, they are not. They need to be installed normally, i.e. by installing the `cockpit-feature` package. But one can e.g. install cockpit-ostree on a classic RPM system, or cockpit-packagekit on an ostree system, and they make sure to become inert.

There *is* a fairly new way to avoid installing any cockpit packages: https://flathub.org/apps/org.cockpit_project.CockpitClient . That can directly connect to any remote system, and all the pages (i.e. html/js/features) are served from the flatpak. The remote system only has to have ssh and python (i.e. like Ansible).

The /usr/local/ question here is really just a shortcut about testing e.g. a cockpit-podman PR -- it's really expensive to go through a full container build and reinstall, if all that we need is to copy a bunch of static files to the target system. That can happen as a sysext, or manually enabling /usr/local/, or setting XDG_DATA_DIRS or a myriad of other things. As I said, this isn't a blocker at all for *us*, it just felt like a bug to me. Especially on a developer machine (desktop or server during development or Ansible) it's rather common to do things like `sudo pip install` or so.

**Comment by cgwalters** [comment]
> The /usr/local/ question here is really just a shortcut about testing

Oh.  Well, there is:

```
bootc usroverlay
dnf install/upgrade ...
```

**Comment by cgwalters** [comment]
Anyways I think we're agreed this is unrelated to bib.  I did https://github.com/containers/bootc/pull/455 related to this.
