### ISSUE TITLE
Target arch with mismatched container arch still builds

### ISSUE THREAD

**Issue by kingsleyzissou** [osbuild/bootc-image-builder#344]
So as things stand it is possible to build an image for a target arch where the container arch is different.

I.e. if you specify `--target-arch x86_64` but the underlying arch of the container is `arm64`, we don't fail.
The image builds and we get the artifacts. As expected though, the artifacts don't boot.

We should probably handle this/fail early.

**Comment by mvo5** [comment]
This should be fixed with https://github.com/osbuild/bootc-image-builder/pull/347 - please reopen if I misread/misremember :)
