### ISSUE TITLE
Bootable container ISO installer fails to initialize `dbus.socket`

### ISSUE THREAD

**Issue by lzap** [osbuild/bootc-image-builder#391]
Hello, trying the build the following bootc:

```
FROM quay.io/centos-bootc/centos-bootc-dev:stream9

RUN dnf -y install httpd && \
    systemctl enable httpd && \
    mv /var/www /usr/share/www && \
    sed -ie 's,/var/www,/usr/share/www,' /etc/httpd/conf/httpd.conf && \
    touch /HTTPD_DEMO

RUN rm /usr/share/httpd/noindex -rf
COPY index.html /usr/share/www/html
EXPOSE 80
```

The resulting ISO can be installed locally via removable media, however, it fails to initialize dbus, thus network manager and the network is offline. That is not a problem for removable media installation, it is for PXE installation.

![image](https://github.com/osbuild/osbuild-composer/assets/49752/d909da77-3e0b-4c8a-9a48-fb66bcbd0c66)

**Comment by mvo5** [comment]
Fwiw, I tried to debug this with `uay.io/centos-bootc/centos-bootc:stream9` and AFAICT `dbus.socket` is not failing there, trying `-dev` now.

**Comment by mvo5** [comment]
Sorry, I cannot reproduce this, here is what I did:
```
$ $ cat Containerfile
FROM quay.io/centos-bootc/centos-bootc-dev:stream9

RUN dnf -y install httpd && \
    systemctl enable httpd && \
    mv /var/www /usr/share/www && \
    sed -ie 's,/var/www,/usr/share/www,' /etc/httpd/conf/httpd.conf && \
    touch /HTTPD_DEMO

RUN rm /usr/share/httpd/noindex -rf
COPY index.html /usr/share/www/html
EXPOSE 80
$ touch index.html
$ sudo podman build -f Containerfile  -t image-issue391
$ mkdir output
$ sudo podman run --rm -it --privileged --pull=newer  --security-opt label=type:unconfined_t -v $(pwd)/output:/output  quay.io/centos-bootc/bootc-image-builder:latest --type iso --local localhost/image-issue391
...
$ cd output/bootiso
$ sudo truncate -s 10G test-disk.img
$ kvm -cpu host -m 1500 -snapshot -cdrom install.iso  -boot d test-disk.img 
...
```
in the booted image I did "sendkey ctrl-alt-f2" and ran "systemctl --failed" and "systemctl status dbus.socket" and got no errors. When running "nmcli" in the booted iso (while it was installing) I saw that it was connected on the ethernet port.

What am I missing :) ?

**Comment by cgwalters** [comment]
> , however, it fails to initialize dbus

Do you have `/var/run` as a physical directory?  https://github.com/CentOS/centos-bootc/issues/140#issuecomment-1946996913

**Comment by lzap** [comment]
@cgwalters is a symlink to `../run`

<img width="602" alt="image" src="https://github.com/osbuild/bootc-image-builder/assets/49752/a01509de-a31a-44c3-8bcd-d2821341c17d">

**Comment by lzap** [comment]
Correction, `dbus.socket` is not **failing**, it does not appear to be **enabled**.

<img width="692" alt="image" src="https://github.com/osbuild/bootc-image-builder/assets/49752/27b92a3d-1b94-4c76-916f-d929465bc0dc">

**Comment by lzap** [comment]
I just noticed I was using `-dev` trying again with `quay.io/centos-bootc/centos-bootc:stream9` instead but getting.

```
xorriso : FAILURE : Image size 1095584s exceeds free space on media 785896s
```

**Comment by lzap** [comment]
So tried to build a clean (base) Fedora ELN, the same result when I PXE boot it.

**Comment by lzap** [comment]
So `uay.io/centos-bootc/centos-bootc:stream9` does boot up correctly, however hitting something different. Need to figure that one out:

<img width="780" alt="image" src="https://github.com/osbuild/bootc-image-builder/assets/49752/a70640c2-1892-4e94-8105-4ec019c991a1">

**Comment by lzap** [comment]
Ok increased VM size to 10GB RAM and it installed, after boot it fails with:

<img width="720" alt="image" src="https://github.com/osbuild/bootc-image-builder/assets/49752/94640024-b603-4039-a4f6-0d552dcb6532">

But I am getting there. Now I will try to build my own container of top of the correct base image.

**Comment by lzap** [comment]
Looks like I was missing this in my KS:

```
%post
bootc switch --mutate-in-place --transport registry quay.io/lzapletal/fedora-eln-bootc-httpd-test
%end
```

And it works now. So the root cause was I was using `-dev` version. I am closing, if you run into this just reopen. Thanks for help.

**Comment by achilleas-k** [comment]
> Looks like I was missing this in my KS:
> 
> ```
> %post
> bootc switch --mutate-in-place --transport registry quay.io/lzapletal/fedora-eln-bootc-httpd-test
> %end
> ```

This should be added automatically by bootc-image-builder when building an ISO.  How was it missing?  Were you replacing the ks with your own?

**Comment by lzap** [comment]
Yeah I am doing PXE installation. Still I am running into an issue when booting the system - bootc is unable to find a commit or something. Not sure why it does not work with my KS: https://gist.github.com/lzap/3ade88a6f8d63ff98af4d0e7cd670059
