### ISSUE TITLE
testing farm ENOSPC again

### ISSUE THREAD

**Issue by cgwalters** [osbuild/bootc-image-builder#401]
Testing Farm is dying on ENOSPC again.

There's lots of potential fixes here; 

- Just get systems provisioned with larger disks (incidentally we should dig in and ensure they're using efficient ephemeral storage and not stock EBS etc)
- "shard" the tests (a good description is [here](https://nexte.st/book/partitioning))
- Ensure we're flushing state between tests (e.g. are we leaking generated disk images?)

**Comment by ondrejbudai** [comment]
Debugging in #414
