### ISSUE TITLE
Add automated testing for .iso

### ISSUE THREAD

**Issue by cdrage** [osbuild/bootc-image-builder#405]
As per https://github.com/osbuild/bootc-image-builder/issues/404 looks like there is no automated testing for iso

**Comment by mvo5** [comment]
This is tested in https://github.com/osbuild/bootc-image-builder/blob/main/test/test_build.py#L421 and this is run in e.g. https://github.com/osbuild/bootc-image-builder/actions/runs/8860993850/job/24332383148?pr=400#step:12:28

But of course the test is always only a snapshot in time and as it uses some external repos there is of course the risk that one of the external repos is broken :(

**Comment by ondrejbudai** [comment]
Yeah, we do have testing for ISOs, but we simply cannot cover all scenarios for external sources like RPM repositories.
