### ISSUE TITLE
Failed to build out quay.io/fedora/fedora-bootc:latest 

### ISSUE THREAD

**Issue by chunfuwen** [osbuild/bootc-image-builder#419]
1.Use below command to build fedora:last image
 sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json   -v /etc/pki:/etc/pki  quay.io/centos-bootc/bootc-image-builder:latest  --type raw --tls-verify=true  --config /config.json  quay.io/fedora/fedora-bootc:latest

2.Throw error: cannot build manifest: cannot get rootfs type for container: container does not include a default root filesystem type

[root@dell-xx~]# sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json   -v /etc/pki:/etc/pki  quay.io/centos-bootc/bootc-image-builder:latest  --type raw --tls-verify=true  --config /config.json  quay.io/fedora/fedora-bootc:latest  --chown 107:107 |tee fail.log
Trying to pull quay.io/centos-bootc/bootc-image-builder:latest...
Getting image source signatures
Copying blob 86b945e95bb7 done   | 
Copying blob e186ae4d41cd done   | 
Copying blob 605514dc1a64 done   | 
Copying config 78b75ba45a done   | 
Writing manifest to image destination
Generating manifest manifest-raw.json
Error: cannot build manifest: cannot get rootfs type for container: container does not include a default root filesystem type
2024/05/04 04:56:20 error: cannot build manifest: cannot get rootfs type for container: container does not include a default root filesystem type

**Comment by chunfuwen** [comment]
This issue also happen to quay.io/fedora/fedora-bootc:40

**Comment by cgwalters** [comment]
Yes this is documented in https://docs.fedoraproject.org/en-US/bootc/qemu-and-libvirt/

(Ultimately of course, we do want to test with different filesystem types too, which is its own thread)

For now, either `xfs` or `ext4` are simple choices, but we should probably have some coverage for `btrfs` too given its usage in other Fedora components.

**Comment by chunfuwen** [comment]
sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json -v /etc/pki:/etc/pki quay.io/centos-bootc/bootc-image-builder:latest --type raw --tls-verify=true --rootfs ext4 --config /config.json quay.io/fedora/fedora-bootc:latest --chown 107:107 

By specifying roofs type, it can build out image successfully, so close this issue

**Comment by chunfuwen** [comment]
this bring some incompatibility when I want to use registry-proxy.engineering.redhat.com/rh-osbs/rhel9-rhel_bootc-image-builder:rhel-9.4 to build latest bootc fedora.
No matter whether I add rootfs  options, it will fail eventually.

```
(.libvirt-ci-venv-ci-runtest-6tctdk) [root@xx libvirt-ci-latest-venv]# sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json   -v /etc/pki:/etc/pki  registry-proxy.engineering.redhat.com/rh-osbs/rhel9-rhel_bootc-image-builder:rhel-9.4  --type raw --tls-verify=true  --config /config.json  quay.io/fedora/fedora-bootc:latest --rootfs ext4
Error: unknown flag: --rootfs
2024/05/05 14:13:07 error: unknown flag: --rootfs



(.libvirt-ci-venv-ci-runtest-6tctdk) [root@xx ibvirt-ci-latest-venv]# sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json   -v /etc/pki:/etc/pki  registry-proxy.engineering.redhat.com/rh-osbs/rhel9-rhel_bootc-image-builder:rhel-9.4  --type raw --tls-verify=true  --config /config.json  quay.io/fedora/fedora-bootc:latest
Generating manifest manifest-raw.json
Error: cannot build manifest: cannot get rootfs type for container: unsupported root filesystem type: , supported: ext4, xfs
2024/05/05 14:15:00 error: cannot build manifest: cannot get rootfs type for container: unsupported root filesystem type: , supported: ext4, xfs
```

**Comment by cgwalters** [comment]
My suggestion in the short term is to change the tests to:

- Use the upstream image quay.io/centos-bootc/bootc-image-builder for Fedora/CentOS
- Use downstream bib for downstream

cc https://github.com/CentOS/centos-bootc/pull/453 which tries to codify this but hasn't spread everywhere yet
