### ISSUE TITLE
Error when using fedora-coreos base image

### ISSUE THREAD

**Issue by sigulete** [osbuild/bootc-image-builder#429]
I used bootc-image-builder to create images from fedora-bootc and centos-bootc base images without a problem. But I can't do the same for fedora-coreos.

I got a message saying "DNF not found." Is this expected? Does this tool use dnf from the base image?

Considering that coreos uses rpm-ostree and not dnf, it would be a problem.

**Comment by achilleas-k** [comment]
Can you provide the output and command you're running?

We don't generally _need_ dnf, strictly speaking, however bootc-image-builder is designed to work with bootc-enabled bootable container images which contain dnf.  For building an ISO, bootc-image-builder needs a container image that has dnf repositories defined so it can use the same packages to build a compatible ISO.

**Comment by sigulete** [comment]
Yes that is correct. I realised that coreos is not the correct base to be used.
I have moved to fedora-bootc and it works fine. However, it only creates RAW images and it doen't work for ISO type.
I will open an next issue with more details.
