### ISSUE TITLE
Can config.yaml / config.toml be readonly?

### ISSUE THREAD

**Issue by cdrage** [osbuild/bootc-image-builder#533]
I don't think bootc-image-builder does anything to the file, could it just be read only?

https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#-build-config : 

```
sudo podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/config.toml:/config.toml \
    -v $(pwd)/output:/output \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type qcow2 \
    quay.io/centos-bootc/centos-bootc:stream9
```

Is it okay to update it to `    -v $(pwd)/config.toml:/config.toml:ro` ?

**Comment by mvo5** [comment]
Yes, great suggestion, I opened a PR
