### ISSUE TITLE
centos 10 stream iso vm is stuck in starting

### ISSUE THREAD

**Issue by chunfuwen** [osbuild/bootc-image-builder#620]
1.  Build out centos stream 10 iso using bib as below:
```
sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json   -v /var/lib/libvirt/images/auth.json:/run/containers/0/auth.json  quay.io/centos-bootc/bootc-image-builder:latest  --type anaconda-iso --tls-verify=true  --config /config.json  quay.io/centos-bootc/centos-bootc:stream10  --chown 107:107  --rootfs ext4 '
```
2. use virt-install to install VM from generated iso with below command:
```
virt-install --name install_upstream_bib_bios_install-centos-bootc --disk path=/var/lib/libvirt/images/install_upstream_bib_bios_install-centos-bootc_bios.qcow2,bus=virtio,format=qcow2,size=12 --vcpus 3 --memory 3096 --osinfo detect=on,require=off --graphics vnc --video virtio --serial pty --wait 10 --cdrom /var/lib/libvirt/images/install_upstream_bib_bios_install-centos-bootc.iso --debug --machine q35 --noreboot
```
3. The VM is stuck in booting as attached screenshot
![Screenshot from 2024-08-26 13-11-48](https://github.com/user-attachments/assets/4ae5b226-a29b-45fe-8201-c7fe2d4d525e)

**Comment by mvo5** [comment]
I started looking into this in my morning and made some progress:
- with the following diff [centos10-iso.diff.txt](https://github.com/user-attachments/files/16745645/centos10-iso.diff.txt)
- it boots to 
![Screenshot from 2024-08-26 09-42-39](https://github.com/user-attachments/assets/226c73af-7ec5-45d9-bcaa-42cbe8cccdc4)

If I manually press "text" install it will finish and reboot and our smoke test works. So it's "just" a matter now of figuring out why it claims `Wayland was unable to start on your machine` and how ti fix that.

**Comment by mvo5** [comment]
Some more data, it seems anaconda is crashing when it tries to read `osbuild.ks`. The error is that it cannot load the ca-certificates bundle while importing the python3-requests package (which it does not really need for getting the file locally fwiw). 

The package is installed in the boot system but it seems it is not part of the initramfs which is (AIUI) when dracut-initqueue is run. 

I'm a bit puzzled that only bib is affected by this, I would assume anything that passes a custom `inst.ks=` would see the same issue. 

![Screenshot from 2024-08-27 10-03-29](https://github.com/user-attachments/assets/e4e2bc66-a61f-4631-a088-e9ef8de4d6fa)

**Comment by mvo5** [comment]
Thanks to @thozza this should be fixed now via https://github.com/osbuild/osbuild/pull/1846 and  https://github.com/osbuild/bootc-image-builder/pull/625- so once a new osbuild with this fix is available on the image this should work.

**Comment by mvo5** [comment]
This seems indeed to be working now, see https://github.com/osbuild/bootc-image-builder/actions/runs/10617103004/job/29429091199?pr=621
```
test/test_build.py::test_iso_installs[quay.io/centos-bootc/centos-bootc:stream10,anaconda-iso] PASSED [ 13%]
```
