### ISSUE TITLE
README example broken

### ISSUE THREAD

**Issue by MoralCode** [osbuild/bootc-image-builder#682]
attempting to run the example in https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#-examples fails with a very generic `Error: repository name must be lowercase`.

There are no uppercase characters I can see in that command:

```
sudo podman pull quay.io/centos-bootc/centos-bootc:stream9
sudo podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/config.toml:/config.toml:ro \
    -v $(pwd)/output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type qcow2 \
    --local \
    quay.io/centos-bootc/centos-bootc:stream9
```

The image pulls just fine and then the main command fails.

System: 
- Kubuntu 24.04.1 LTS

**Comment by achilleas-k** [comment]
> attempting to run the example in https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#-examples fails with a very generic `Error: repository name must be lowercase`.
> 

Can you paste the full output?  This isn't an error from bootc-image-builder (or any part of osbuild/images or osbuild afaict), so it's probably from one of the underlying tools.

**Comment by MoralCode** [comment]
Tried to verify this (now with much more space free on my filesystem) and wasnt able to verify it

**Comment by MoralCode** [comment]
I replicated this again

was trying to follow the firmware fetching part of https://mrguitar.net/?p=2605

ran `sudo podman run -ti --rm -v $(pwd)/tmp:/tmp fedora-bootc /tmp/get-firmware.sh`

saw `Error: repository name must be lowercase`

i assume this is on me for not using the full url for `fedora-bootc` somehow? not sure how that would impact the README example tho

**Comment by MoralCode** [comment]
seems like the issue is just spaces and caps in the filename with the unquoted  `$(pwd)`

**Comment by achilleas-k** [comment]
The `$(pwd)` is actually not needed at all, `-v ./tmp:/tmp` should work just fine.  I wrote the initial docs with `$(pwd)` like a year ago and it just stuck.  Let's get rid of it.

**Comment by achilleas-k** [comment]
#739
