### ISSUE TITLE
enable FIPS in kernel args at install time for anaconda-iso builds

### ISSUE THREAD

**Issue by stevenperaltaf5** [osbuild/bootc-image-builder#708]
when settings FIPS to true in blueprint, kernel args for the install ISO should be appended with `fips=1` so that our system boots with the kernel in FIPS mode during installation

an example config.toml:
```toml
[customizations]
fips = true

[customizations.installer.kickstart]
contents = """
text --non-interactive
network --bootproto=dhcp --device=eno1 --activate --onboot=on

rootpw --lock --iscrypted locked
user --name admin --password admin --groups wheel

zerombr
clearpart --all --initlabel --disklabel=gpt
autopart --noswap --type=lvm

reboot
"""
```

after building the image, the resultant manifest doesn't show any indication that `fips=1` has been added to the kernel args in the `org.osbuild.grub2.iso` stage of the `efiboot-tree` pipeline:
```json
{
  "version": "2",
  "pipelines": [
    ...
    {
      "name": "efiboot-tree",
      "build": "name:build",
      "stages": [
        {
          "type": "org.osbuild.grub2.iso",
          "options": {
            "product": {
              "name": "AlmaLinux",
              "version": "9.4"
            },
            "kernel": {
              "dir": "/images/pxeboot",
              "opts": [
                "inst.stage2=hd:LABEL=Container-Installer-aarch64",
                "inst.ks=hd:LABEL=Container-Installer-aarch64:/osbuild.ks"
              ]
            },
            "isolabel": "Container-Installer-aarch64",
            "architectures": [
              "AA64"
            ],
            "vendor": "almalinux"
          }
        }
      ]
    },
    ...
  ]
  ...
}
```

viewing the kernel args in the grub boot menu option shows that `fips=1` hasn't been appended:
![Screenshot 2024-11-08 at 9 58 28 PM](https://github.com/user-attachments/assets/246d693f-885d-42bb-8b52-05e3047e85e1)

after installation, `fips-mode-setup --check` yields a "FIPS mode is disabled." response:
![image](https://github.com/user-attachments/assets/a0dfe149-62e5-4f83-a386-51b91408ded5)

**Comment by henrywang** [comment]
Does this feature conflict with the other non iso/anaconda-iso image type which enabled FIPS in base image https://gitlab.com/fedora/bootc/base-images/-/merge_requests/31? Thanks.

**Comment by cgwalters** [comment]
> Does this feature conflict with the other non iso/anaconda-iso image type which enabled FIPS in base image https://gitlab.com/fedora/bootc/base-images/-/merge_requests/31? Thanks.


No we need to do both, see https://docs.fedoraproject.org/en-US/bootc/security-and-hardening/#_usage_with_anaconda

**Comment by stevenperaltaf5** [comment]
I see #709 was merged, can we consider this ticket closed?
