### ISSUE TITLE
podman run has no --type parameter

### ISSUE THREAD

**Issue by dilyanpalauzov** [osbuild/bootc-image-builder#735]
The example from README.md contains
```
sudo podman run … --type qcow2 --local quay.io/centos-bootc/centos-bootc:stream9
```
The documentation for podman run at https://docs.podman.io/en/latest/markdown/podman-run.1.html does not mention the --type and --local parameters.

**Comment by ondrejbudai** [comment]
These are arguments for bootc-image-builder, not for podman, they are specified after the image reference in the podman run command. Have you actually encountered an issue with the command?

**Comment by dilyanpalauzov** [comment]
Yes, you are right that the parameters are to the image, not to `podman run`.  I have not encountered problems with the command.

Where do I find information about the `--local` parameter?

**Comment by ondrejbudai** [comment]
ugh, it's not very well documented at the moment. The `--local` flag tells bootc-image-builder to use bootable container images from a local containers storage (mounted inside bootc-image-builder via `-v /var/lib/containers/storage:/var/lib/containers/storage`. This the recommended way to use bootc-image-builder. We even make it the default in https://github.com/osbuild/bootc-image-builder/pull/423.

If you don't specify `--local`, bootc-image-builder pulls the bootable container image itself.
