### ISSUE TITLE
Unable to build images that are not based on Fedora 39

### ISSUE THREAD

**Issue by noelmiller** [osbuild/bootc-image-builder#88]
Hey folks! 

I have attempted to build some images using this tool for the Universal Blue team and we are unable to build images that are not based on Fedora 39. 
The 2 images I have tried: 
ghcr.io/ublue-os/bluefin:gts (Based on Fedora 38)
ghcr.io/ublue-os/ucore:latest (Based on Fedora CoreOS 37)

I was talking with @achilleas-k and it might be related to using the Fedora 39 tools for building the images and them not being backwards compatible to build older versions of Fedora.

Happy to help test where I can!

Thanks, 

Noel

**Comment by cgwalters** [comment]
This will also be fixed by https://github.com/osbuild/bootc-image-builder/issues/18

**Comment by ondrejbudai** [comment]
This is basically #20, let's close this one to deduplicate a bit. We are working on it. :)
