### ISSUE TITLE
Use local container image, don't require fetching from registry

### ISSUE THREAD

**Issue by noelmiller** [osbuild/bootc-image-builder#90]
For testing containers before pushing them to well-known container registries, it would be nice to utilize this tool to build images from local or private container registries.

**Comment by cdrage** [comment]
@ondrejbudai @deboer-tim @cgwalters 

This is a blocker for Podman Desktop, we would need this in order to avoid having to `podman push` the image to run `bootc-image-builder`

**Comment by ondrejbudai** [comment]
@kingsleyzissou are working on it. He's sick today, though, so I'm not sure when we will be able to finish that.

**Comment by noelmiller** [comment]
I was able to get this work recently using the following example: 
```
sudo podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --net=host \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/config.json:/config.json \
    -v $(pwd)/output:/output \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type qcow2 \
    --config /config.json \
    --tls-verify=false \
    localhost:5000/silverblue-smoketest:latest
```

**Comment by ondrejbudai** [comment]
We want to support the local container storage without an intermediate local registry, though. Let's reopen this until the proper thing lands.

**Comment by kingsleyzissou** [comment]
There is a WIP pr for this here https://github.com/osbuild/osbuild/pull/1550

**Comment by vrothberg** [comment]
We chatted about this issue this week and my understanding is that it's close to being fixed.  Since https://github.com/osbuild/osbuild/pull/1550 has been closed, can we link the missing pieces here to facilitate tracking the progress?

**Comment by ondrejbudai** [comment]
Implemented in https://github.com/osbuild/bootc-image-builder/pull/120, see https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#using-local-containers for docs.

**Comment by vrothberg** [comment]
Great work, thanks to you and the team, @ondrejbudai !
